### ISSUE TITLE
Tests failing on master branch ?

### ISSUE THREAD

**Issue by zedtux** [leikind/wice_grid_testbed#4]
Hello,

Before to fix the slim integration, I want to be able to run all the tests and have then in green.
Unfortunately, it looks like it's not the case from the master branch.

First of all, I had to upgrade the selenium driver due to the Firefox upgrades, which is not a problem. 
I have also noticed that the version of the `nice_grid` gem in the master branch is not the latest one. I will do the upgrade (this includes a Rails upgrade from 3.x to 4.x) in a separated branch.

Then the tests are running but with some failures:

```
Failures:

  1) basisc3 WiceGrid should filter by Due Date
     Failure/Error: page.should have_content('1-20 / 35')
       expected to find text "1-20 / 35" in "1-20 / 50 show all"
     # ./spec/features/shared.rb:552:in `block (3 levels) in <top (required)>'
     # ./spec/features/shared.rb:551:in `block (2 levels) in <top (required)>'

  2) blockless_column_definition WiceGrid should filter by Due Date
     Failure/Error: page.should have_content('1-20 / 35')
       expected to find text "1-20 / 35" in "1-20 / 50 show all"
     # ./spec/features/shared.rb:552:in `block (3 levels) in <top (required)>'
     # ./spec/features/shared.rb:551:in `block (2 levels) in <top (required)>'

  3) custom_ordering WiceGrid should be sorted by the length of the word
     Failure/Error: page.should have_content('Duplicate')
       expected to find text "Duplicate" in "Postponed"
     # ./spec/features/custom_ordering_request_spec.rb:22:in `block (3 levels) in <top (required)>'
     # ./spec/features/custom_ordering_request_spec.rb:21:in `block (2 levels) in <top (required)>'

  4) dates WiceGrid should filter by Due Date
     Failure/Error: month_select = context.find(:css, '.ui-datepicker-month')
     Capybara::ElementNotFound:
       Unable to find css ".ui-datepicker-month"
     # ./spec/features/shared.rb:532:in `set_datepicker'
     # ./spec/features/shared.rb:545:in `block (2 levels) in <top (required)>'

  5) current_page_records & all_pages_records WiceGrid should return records displayed on the page and throughout all pages
     Failure/Error: page.should have_content('10 records on the current page: 540, 519, 507, 537, 551, 515, 511, 524, 542, and 523')
       expected to find text "10 records on the current page: 540, 519, 507, 537, 551, 515, 511, 524, 542, and 523" in "WiceGrid 3.4.1 examples ← Previous Next → BASICS Most simple grid Named columns Two pagination panels Associating columns with database fields Dropping the block in #column Numeric filters More than 1 grid on a page Disabling filters Disabling all filters Date/Datetime helpers Hidden filter panel Disabling ordering Initial conditions and ordering External submit/reset buttons External filters External filters (example with 2 grids) A grid without records JOINED TABLES Joined tables 2 associations to the same table CUSTOM FILTERS AND ORDERING Custom ordering Custom filters (one table) Custom filters (joined tables) Custom filters (method chains) Custom filters: turning off multiple selection Custom filters (null values) MISCELLANEOUS Styling the grid Text filters with negation Adding custom rows Removing link \"All Records\" CSV export CSV export and external filters Auto reloading filters Auto reloading filters (external filters) Auto reloading filters (two grids on page) INTEGRATION WITH THE APPLICATION Action column Hiding certain checkboxes in the action column Integration with other forms View helpers to access records on the current page and all pages Callback to process records of the current page Callback to process records throughout all pages on demand Localization Generating custom filter parameters Saved queries: simple example View helpers to access records on the current page and all pages Method current_page_records sent to the grid object returns a list of all ActiveRecord objects currently displayed on the page. Method all_pages_records returns a list of all ActiveRecord objects throughout all pages of the current selection. all_pages_records causes an additional SQL query to be executed and has to be used with care. Both methods can be used after the grid definition only. app/controllers/integration_with_application_view_controller.rb app/views/integration_with_application_view/_grid.html.erb app/views/integration_with_application_view/index.html.haml ID Title Priority Status Project Name Archived Added -- Anecdotic High Low Normal Urgent -- Assigned Cancelled Closed Duplicate New Postponed Resolved Started Verified -- Divine Firmware Super Game Ultimate Website -- yes no 1 2 3 4 5 » 1-10 / 50 show all 519 consequatur minus et Low Assigned Ultimate Website No 22 Sep 22:11 537 ut ipsum excepturi Assigned Ultimate Website No 02 Oct 22:11 540 inventore architecto aut Urgent Assigned Ultimate Website No 22 Aug 22:11 507 sed impedit iste Assigned Ultimate Website No 13 Sep 22:11 511 est maiores delectus Normal Cancelled Super Game No 25 Oct 22:11 531 veniam tempora Urgent Cancelled Super Game No 18 Aug 22:11 527 voluptates corporis velit Cancelled Super Game No 11 Oct 22:11 515 voluptatum non High Cancelled Super Game No 29 Sep 22:11 523 dolores delectus Cancelled Ultimate Website No 16 Nov 22:11 524 quod dolor inventore Low Cancelled Ultimate Website Yes 07 Oct 22:11 10 records on the current page: 519, 537, 540, 507, 511, 531, 527, 515, 523, and 524 50 records throughout all pages: 537, 540, 519, 507, 531, 542, 511, 515, 527, 551, 523, 524, 539, 535, 532, 518, 520, 546, 512, 514, 522, 543, 550, 552, 521, 516, 544, 541, 510, 553, 528, 529, 513, 508, 548, 556, 547, 555, 525, 534, 536, 538, 526, 517, 545, 549, 509, 554, 530, and 533 © Yury Leikind 2012 Sources"
     # ./spec/features/integration_with_application_view_request_spec.rb:11:in `block (2 levels) in <top (required)>'

  6) with_resultset WiceGrid should show records displayed on all pages
     Failure/Error: page.should have_content('50 records on all pages: 540, 519, 507, 537, 531, 551, 515, 511, 524, 542, 523, 527, 518, 535, 539, 520, 532, 512, 514, 522, 546, 516, 521, 544, 543, 550, 552, 510, 541, 553, 529, 508, 513, 528, 556, 548, 547, 525, 534, 555, 549, 536, 545, 509, 517, 538, 526, 554, 530, and 533')
       expected to find text "50 records on all pages: 540, 519, 507, 537, 531, 551, 515, 511, 524, 542, 523, 527, 518, 535, 539, 520, 532, 512, 514, 522, 546, 516, 521, 544, 543, 550, 552, 510, 541, 553, 529, 508, 513, 528, 556, 548, 547, 525, 534, 555, 549, 536, 545, 509, 517, 538, 526, 554, 530, and 533" in "ID Title Priority Status Project Name Archived Added -- Anecdotic High Low Normal Urgent -- Assigned Cancelled Closed Duplicate New Postponed Resolved Started Verified -- Divine Firmware Super Game Ultimate Website -- yes no 1 2 3 4 5 ... 9 10 » 1-5 / 50 show all 507 sed impedit iste Assigned Ultimate Website No 13 Sep 22:11 519 consequatur minus et Low Assigned Ultimate Website No 22 Sep 22:11 537 ut ipsum excepturi Assigned Ultimate Website No 02 Oct 22:11 540 inventore architecto aut Urgent Assigned Ultimate Website No 22 Aug 22:11 511 est maiores delectus Normal Cancelled Super Game No 25 Oct 22:11 50 records on all pages: 537, 540, 519, 507, 531, 542, 511, 515, 527, 551, 523, 524, 539, 535, 532, 518, 520, 546, 512, 514, 522, 543, 550, 552, 521, 516, 544, 541, 510, 553, 528, 529, 513, 508, 548, 556, 547, 555, 525, 534, 536, 538, 526, 517, 545, 549, 509, 554, 530, and 533"
     # ./spec/features/resultset_processings2_request_spec.rb:14:in `block (3 levels) in <top (required)>'
     # ./spec/features/resultset_processings2_request_spec.rb:13:in `block (2 levels) in <top (required)>'

  7) with_resultset WiceGrid should show records displayed on all pages with a custom filter selection
     Failure/Error: page.should have_content('8 records on all pages: 531, 551, 515, 511, 524, 542, 523, and 527')
       expected to find text "8 records on all pages: 531, 551, 515, 511, 524, 542, 523, and 527" in "ID Title Priority Status Project Name Archived Added -- Anecdotic High Low Normal Urgent -- Assigned Cancelled Closed Duplicate New Postponed Resolved Started Verified -- Divine Firmware Super Game Ultimate Website -- yes no 1 2 » 1-5 / 8 show all 511 est maiores delectus Normal Cancelled Super Game No 25 Oct 22:11 523 dolores delectus Cancelled Ultimate Website No 16 Nov 22:11 524 quod dolor inventore Low Cancelled Ultimate Website Yes 07 Oct 22:11 531 veniam tempora Urgent Cancelled Super Game No 18 Aug 22:11 542 accusantium Anecdotic Cancelled Ultimate Website No 06 Sep 22:11 8 records on all pages: 511, 515, 523, 524, 527, 531, 542, and 551"
     # ./spec/features/resultset_processings2_request_spec.rb:38:in `block (3 levels) in <top (required)>'
     # ./spec/features/resultset_processings2_request_spec.rb:37:in `block (2 levels) in <top (required)>'

  8) with_resultset WiceGrid should return records displayed on the page
     Failure/Error: page.should have_content('10 records on the current page: 540, 519, 507, 537, 551, 515, 511, 524, 542, and 523')
       expected to find text "10 records on the current page: 540, 519, 507, 537, 551, 515, 511, 524, 542, and 523" in "WiceGrid 3.4.1 examples ← Previous Next → BASICS Most simple grid Named columns Two pagination panels Associating columns with database fields Dropping the block in #column Numeric filters More than 1 grid on a page Disabling filters Disabling all filters Date/Datetime helpers Hidden filter panel Disabling ordering Initial conditions and ordering External submit/reset buttons External filters External filters (example with 2 grids) A grid without records JOINED TABLES Joined tables 2 associations to the same table CUSTOM FILTERS AND ORDERING Custom ordering Custom filters (one table) Custom filters (joined tables) Custom filters (method chains) Custom filters: turning off multiple selection Custom filters (null values) MISCELLANEOUS Styling the grid Text filters with negation Adding custom rows Removing link \"All Records\" CSV export CSV export and external filters Auto reloading filters Auto reloading filters (external filters) Auto reloading filters (two grids on page) INTEGRATION WITH THE APPLICATION Action column Hiding certain checkboxes in the action column Integration with other forms View helpers to access records on the current page and all pages Callback to process records of the current page Callback to process records throughout all pages on demand Localization Generating custom filter parameters Saved queries: simple example Callback to process records of the current page In addition to current_page_records and current_page_records helpers a callback can be setup in the controller which is executed when a grid page is rendered. Though the results of that processing is rendered on page, normally such callbacks are used for some kind of background processing. Please notice that the callback is executed after the controller action and thus all controller instance variables have already been injected inti the view, that is why the current example has a definition of @one_page_records before the callback, so that the object is injected into the view and the callback block has access to the object as well. The callback can be setup separately as a block: @grid.with_paginated_resultset do |records| ... end or as an argument of initialize_grid where the value is the name of the method to be invoked: @grid = initialize_grid(Task, with_paginated_resultset: :process_records ) app/controllers/resultset_processings_controller.rb app/views/resultset_processings/_grid.html.erb app/views/resultset_processings/index.html.haml ID Title Priority Status Project Name Archived Added -- Anecdotic High Low Normal Urgent -- Assigned Cancelled Closed Duplicate New Postponed Resolved Started Verified -- Divine Firmware Super Game Ultimate Website -- yes no 1 2 3 4 5 » 1-10 / 50 show all 507 sed impedit iste Assigned Ultimate Website No 13 Sep 22:11 519 consequatur minus et Low Assigned Ultimate Website No 22 Sep 22:11 537 ut ipsum excepturi Assigned Ultimate Website No 02 Oct 22:11 540 inventore architecto aut Urgent Assigned Ultimate Website No 22 Aug 22:11 524 quod dolor inventore Low Cancelled Ultimate Website Yes 07 Oct 22:11 527 voluptates corporis velit Cancelled Super Game No 11 Oct 22:11 511 est maiores delectus Normal Cancelled Super Game No 25 Oct 22:11 515 voluptatum non High Cancelled Super Game No 29 Sep 22:11 531 veniam tempora Urgent Cancelled Super Game No 18 Aug 22:11 523 dolores delectus Cancelled Ultimate Website No 16 Nov 22:11 10 records on the current page: 507, 519, 537, 540, 524, 527, 511, 515, 531, and 523 © Yury Leikind 2012 Sources"
     # ./spec/features/resultset_processings_request_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 13 minutes 2.76 seconds
254 examples, 8 failures, 70 pending

Failed examples:

rspec ./spec/features/shared.rb:541 # basisc3 WiceGrid should filter by Due Date
rspec ./spec/features/shared.rb:541 # blockless_column_definition WiceGrid should filter by Due Date
rspec ./spec/features/custom_ordering_request_spec.rb:10 # custom_ordering WiceGrid should be sorted by the length of the word
rspec ./spec/features/shared.rb:541 # dates WiceGrid should filter by Due Date
rspec ./spec/features/integration_with_application_view_request_spec.rb:9 # current_page_records & all_pages_records WiceGrid should return records displayed on the page and throughout all pages
rspec ./spec/features/resultset_processings2_request_spec.rb:9 # with_resultset WiceGrid should show records displayed on all pages
rspec ./spec/features/resultset_processings2_request_spec.rb:31 # with_resultset WiceGrid should show records displayed on all pages with a custom filter selection
rspec ./spec/features/resultset_processings_request_spec.rb:9 # with_resultset WiceGrid should return records displayed on the page
```

**Comment by zedtux** [comment]
Did I made something wrong or can you confirm this issue ?

**Comment by zedtux** [comment]
Also I had to comment the code from the following spec files in order to get the tests running:
- spec/helpers/integration_with_application_helper_spec.rb
- spec/helpers/localization_helper_spec.rb

**Comment by zedtux** [comment]
The previous test failure report has been generated with PostgreSQL. With MySQL I have the following output:

```
Failures:

  1) basisc3 WiceGrid should filter by Due Date
     Failure/Error: page.should have_content('1-20 / 35')
       expected to find text "1-20 / 35" in "1-20 / 50 show all"
     # ./spec/features/shared.rb:552:in `block (3 levels) in <top (required)>'
     # ./spec/features/shared.rb:551:in `block (2 levels) in <top (required)>'

  2) blockless_column_definition WiceGrid should filter by Due Date
     Failure/Error: page.should have_content('1-20 / 35')
       expected to find text "1-20 / 35" in "1-20 / 50 show all"
     # ./spec/features/shared.rb:552:in `block (3 levels) in <top (required)>'
     # ./spec/features/shared.rb:551:in `block (2 levels) in <top (required)>'

  3) dates WiceGrid should filter by Due Date
     Failure/Error: month_select = context.find(:css, '.ui-datepicker-month')
     Capybara::ElementNotFound:
       Unable to find css ".ui-datepicker-month"
     # ./spec/features/shared.rb:532:in `set_datepicker'
     # ./spec/features/shared.rb:545:in `block (2 levels) in <top (required)>'

Finished in 10 minutes 13.77 seconds
254 examples, 3 failures, 70 pending
```

**Comment by leikind** [comment]
Please ignore master. This is Rails 2 :)

**Comment by leikind** [comment]
I mean  ignore brach `master` in the gem. As for this app, ignore all branches but for `rails4`.

**Comment by zedtux** [comment]
OMG I haven't realise that there is a `rails4` branch ... :dizzy_face:

Why not creating a `rails2` branch and then merge `rails4` in `master` instead ? It would make more sense, right ?

**Comment by leikind** [comment]
Sorry for this. I think up to now I was the only user of this code.

> Why not creating a rails2 branch and then merge rails4 in master instead ? It would make more sense, right ?

Yes, you are right

**Comment by zedtux** [comment]
With the `rails4` branch, it's much better :)

Do you want me to do the branches update or will you do it ?

**Comment by leikind** [comment]
If you want please do, if not I will do it this weekend, I don't have time now. If you do, please find all mentions of branches in README and correct them. Thank you

and I need to  release 3.6.0.pre5 as 3.6.0.

**Comment by zedtux** [comment]
Do you mind if I change the README file from Ruby doc to Markdown ?

**Comment by leikind** [comment]
sure go ahead

**Comment by zedtux** [comment]
@leikind I can't create the `rails2` branch from `master` as I don't have the write permission on this repo, so I have prepared the needed PR.

You should then:
1. Accept the PR #6 which updates the README file.
2. Create the `rails2` branch from the `master` branch.
3. Accept the PR #7 which merge the `rails4` branch in the `master` branch.
4. Finally accept the PR #5 in order to get a newer version of the selenium driver which allows to run the tests with a newer version of Firefox.

Let me know if something looks wrong or if I can help.

**Comment by leikind** [comment]
would it be easier if I just give you access to this repo?

**Comment by zedtux** [comment]
yes sure !

**Comment by leikind** [comment]
hold on. I think there is a misunderstanding.

This :

> Why not creating a rails2 branch and then merge rails4 in master instead ? It would make more sense, right ?

is about the plugin, not this app. In this app it's only rails4 that counts. So step 2 is not needed. Giving you access now

**Comment by leikind** [comment]
done, you are a contributor

**Comment by zedtux** [comment]
Thank you @leikind. Let's rock ! :)

**Comment by zedtux** [comment]
@leikind I did few modifications in order to get bulls running on a CI, like Travis-ci. I don't have access to the settings, so can you please configure Travis-CI for this repo please ?

**Comment by leikind** [comment]
I've enabled Travis-ci for wice_grid_testbed. Anything else?

**Comment by zedtux** [comment]
Thank you ! It looks good for now : https://travis-ci.org/leikind/wice_grid_testbed/builds/108042792. Let see if there are the same errors on the CI.

**Comment by zedtux** [comment]
@leikind so Travis is now working with PostgreSQL and MySQL for the Ruby version 2.2.3, 2.2.4 and 2.3.0 (You can change the ruby versions based on [the list of supported ruby versions](http://rubies.travis-ci.org)).

There are some failing tests impacting both cases: [MySQL](https://travis-ci.org/leikind/wice_grid_testbed/jobs/108307218) and [PostgreSQL](https://travis-ci.org/leikind/wice_grid_testbed/jobs/108307220) and some other tests failing only for PostgreSQL (default database ordering is different).

**Comment by leikind** [comment]
awesome work

On Wed, Feb 10, 2016 at 5:10 PM, Guillaume Hain notifications@github.com
wrote:

> @leikind https://github.com/leikind so Travis is now working with
> PostgreSQL and MySQL for the Ruby version 2.2.3, 2.2.4 and 2.3.0 (You can
> change the ruby versions based on the list of supported ruby version).
> 
> There are some failing tests impacting both cases: MySLQ and PostgreSQL
> and some other tests failing only for PostgreSQL (default database ordering
> is different).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/leikind/wice_grid_testbed/issues/4#issuecomment-182451073
> .

## 

Best regards,
Yuri Leikind

Sent from my Nokia 3310

**Comment by zedtux** [comment]
I have solved the tests about selecting multiple options from a select with the MySQL DB so that now [4 tests are failing with MySQL](https://travis-ci.org/leikind/wice_grid_testbed/jobs/108329636) and [14 tests are failing for PostgreSQL](https://travis-ci.org/leikind/wice_grid_testbed/jobs/108329637).

**Comment by leikind** [comment]
are you are fixing plugin code, too?

**Comment by zedtux** [comment]
Well I'm doing my best to fix the tests but unfortunately all the tests pass on my local machine with MySQL, while it remains 4 failing tests on the CI.

Of course, you should be the right guy to fix the tests as you know by heart the plugin, but I'm trying to figure out how to solve them by myself ;)

**Comment by zedtux** [comment]
No activities for almost 2 years ... closing the issue.
